apiVersion: argocroj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: vault
    targetRevision: "0.30.0"
    helm:
      values: |
        server:
          standalone:
            enabled: true
          dataStorage:
            enabled: true
            size: 1Gi
        injector:
          enabled: true
          externalVaultAddr: "http://vault.vault.svc.cluster.local:8200"
          agentDefaults:
            tempSMPC:
              enabled: true
            templateConfig:
              exitOnRetryFailure: true
        global:
          enabled: true
          tlsDisable: true
    destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true