# NOTE (Production Hardening): In a real-world scenario, 'tlsDisable' would be false.
# For GKE, we would implement Auto-Unseal using Cloud KMS and Workload Identity.
# Reference: https://developer.hashicorp.com/vault/docs/concepts/seal#gcpckms
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: vault
    targetRevision: "0.30.0"
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: true
        server:
          standalone:
            enabled: true
          dataStorage:
            enabled: true
            size: 1Gi
        injector:
          enabled: true
          externalVaultAddr: "http://vault.vault.svc.cluster.local:8200"
          agentDefaults:
            templateConfig:
              exitOnRetryFailure: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
