---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rivce06/sre-agent.git
    targetRevision: feat
    path: deploy/base
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
